import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ProviderWrapper from "./components/dynamic-wrapper";
import Header from "./components/header";
import { ContextProvider } from './context/context';
const inter = Inter({ subsets: ["latin"] });
import { initMoralis } from './lib/moralis';

initMoralis();
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>
          <ProviderWrapper>
            <Header />
            {children}
          </ProviderWrapper>
        </ContextProvider>
      </body>
    </html>
  );
}
